[project]
name = "tktor"
version = "0.1.0"
description = ""
authors = [
    {name = "enchance",email = "enchance@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
]

[tool.poetry.group.dev.dependencies]
alembic = "^1.15.1"
sqlmodel = "^0.0.24"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"